version: 2
registries:
  gradle-plugin-portal:
    type: maven-repository
    url: https://plugins.gradle.org/m2
    username: dummy # Required by dependabot
    password: dummy # Required by dependabot
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/dependencyManagement"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/conventions"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/gradle-plugins"
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    allow:
      - dependency-name: "com.gradle*"
    registries:
      - gradle-plugin-portal
    rebase-strategy: "disabled"
    schedule:
      interval: "daily"
