otel:
  instrumentation:
    logback-appender:
      experimental:
        capture-code-attributes: true
  propagators:
    - b3
  resource:
    attributes:
      applicationYaml: "true" # boolean doesn't work here
