name: Build

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  common:
    uses: ./.github/workflows/build-common.yml
    secrets:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
      GE_CACHE_USERNAME: ${{ secrets.GE_CACHE_USERNAME }}
      GE_CACHE_PASSWORD: ${{ secrets.GE_CACHE_PASSWORD }}

  muzzle:
    # release branches are excluded
    # because any time a new library version is released to maven central it can fail
    # which requires unnecessary release branch maintenance, especially for patches
    if: ${{ !startsWith(github.ref_name, 'release/') }}
    uses: ./.github/workflows/reusable-muzzle.yml

  gradle-plugins:
    uses: ./.github/workflows/reusable-gradle-plugins.yml

  misspell-check:
    # release branches are excluded to avoid unnecessary maintenance if new misspellings are added
    # to the misspell dictionary
    if: ${{ !startsWith(github.ref_name, 'release/') }}
    uses: ./.github/workflows/reusable-misspell-check.yml
