name: Build (daily, --no-build-cache)

on:
  schedule:
    # strange schedule to reduce the risk of DDOS GitHub infra
    - cron: "48 4 * * *"
  workflow_dispatch:

jobs:
  required-jobs:
    uses: ./.github/workflows/reusable-required-jobs.yml
    with:
      no-build-cache: true
    secrets:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

  test-latest-deps:
    uses: ./.github/workflows/reusable-test-latest-deps.yml
    with:
      no-build-cache: true
    secrets:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

  # muzzle is not included here because it doesn't use gradle cache anyway and so is already covered
  # by the normal daily build

  # markdown-link-check and misspell-check are not included here because they don't use gradle cache
  # anyway and so are already covered by the normal daily build

  open-issue-on-failure:
    needs:
      - required-jobs
      - test-latest-deps
    if: failure()
    uses: ./.github/workflows/reusable-open-issue-on-failure.yml
