name: Muzzle

on:
  workflow_call:
    inputs:
      cache-read-only:
        type: boolean
        required: false

jobs:
  muzzle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Run muzzle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: instrumentation:muzzle --max-workers=4
          cache-read-only: ${{ inputs.cache-read-only }}
