name: Overhead benchmark (daily)
on:
  schedule:
    # daily at 5:00 UTC
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  run-overhead-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Copy results from gh-pages branch
        run: |
          rsync -avv gh-pages/benchmark-overhead/results/ benchmark-overhead/results/

      - name: Run tests
        uses: gradle/actions/setup-gradle@1168cd3d07c1876a65e1724114de42ccbdfa7b78 # v3.2.1
        with:
          arguments: test
          build-root-directory: benchmark-overhead

      - name: Inspect the results dir
        working-directory: benchmark-overhead
        run: ls -lR results

      - name: Copy results back to gh-pages branch
        run: rsync -avv benchmark-overhead/results/ gh-pages/benchmark-overhead/results/ && rm -rf benchmark-overhead/results

      - name: Commit updated results
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          add: "benchmark-overhead/results"
          cwd: "./gh-pages"
          branch: "gh-pages"
          message: "update test result data"
          author_name: opentelemetrybot
          author_email: 107717825+opentelemetrybot@users.noreply.github.com
          committer_name: opentelemetrybot
          committer_email: 107717825+opentelemetrybot@users.noreply.github.com

  workflow-notification:
    needs:
      - run-overhead-tests
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: ${{ needs.run-overhead-tests.result == 'success' }}
