name: PR build Quarkus images for smoke tests

on:
  pull_request:
    paths:
      - "smoke-tests/images/quarkus/**"
      - ".github/workflows/pr-smoke-test-quarkus-images.yml"
      - ".github/workflows/reusable-smoke-test-images.yml"
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      project: ":smoke-tests:images:quarkus"
      cache-read-only: true
      # Quarkus 3.7+ requires Java 17+
      skip-java-8: true
      skip-java-11: true

  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Set up Gradle cache
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
        with:
          cache-read-only: true

      - name: Build Java 17 Docker image
        run: ./gradlew :smoke-tests:images:quarkus:jibDockerBuild -Ptag=local -PtargetJDK=17 -Djib.httpTimeout=120000 -Djib.console=plain

      - name: Build Java 21 Docker image
        run: ./gradlew :smoke-tests:images:quarkus:jibDockerBuild -Ptag=local -PtargetJDK=21 -Djib.httpTimeout=120000 -Djib.console=plain

      - name: Build Java 23 Docker image
        run: ./gradlew :smoke-tests:images:quarkus:jibDockerBuild -Ptag=local -PtargetJDK=23 -Djib.httpTimeout=120000 -Djib.console=plain

      - name: Verify
        run: ./gradlew :smoke-tests:test -PsmokeTestSuite=quarkus
