name: PR build Servlet images for smoke tests

on:
  pull_request:
    paths:
      - 'smoke-tests/images/servlet/**'
      - '.github/workflows/pr-smoke-test-servlet-images.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
          - ubuntu-latest
        smoke-test-server:
          - jetty
          - liberty
          - payara
          - tomcat
          - tomee
          - websphere
          - wildfly
        exclude:
          - os: windows-2019
            smoke-test-server: websphere
      fail-fast: false
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
        if: matrix.os == 'windows-2019'

      - uses: actions/checkout@v3

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Set up gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: true

      - name: Build Linux docker images
        if: matrix.os != 'windows-2019'
        run: ./gradlew buildLinuxTestImages -PsmokeTestServer=${{ matrix.smoke-test-server }}
        working-directory: smoke-tests/images/servlet

      - name: Build Windows docker images
        if: matrix.os == 'windows-2019'
        run: ./gradlew buildWindowsTestImages -PsmokeTestServer=${{ matrix.smoke-test-server }}
        working-directory: smoke-tests/images/servlet
