name: PR test latest deps

on:
  pull_request:
    types:
      - labeled

concurrency:
  group: pr-test-latest-deps-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  testLatestDeps:
    runs-on: ubuntu-latest
    # testLatestDeps is not included in the PR workflow by default
    # because any time a new library version is released to maven central
    # it can fail due to test code incompatibility with the new library version,
    # or due to slight changes in emitted telemetry, which can be confusing for contributors
    # (muzzle can also fail when a new library version is released to maven central
    # but that happens much less often)
    if: ${{ contains(github.event.pull_request.labels.*.name, 'test latest deps') }}
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test -PtestLatestDeps=true
          cache-read-only: true
