name: PR build

on: pull_request

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Debug space
        run: df -h

      - name: Test
        uses: burrunan/gradle-cache-action@v1.5
        with:
          job-id: jdk11
          arguments: :smoke-tests:test

      - name: Debug space
        if: always()
        run: df -h

      - name: Aggregate test reports with ciMate
        if: always()
        continue-on-error: true
        env:
          CIMATE_PROJECT_ID: mz1jo49x
          CIMATE_CI_KEY: "PR / smoke"
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate -v "**/TEST-*.xml"