name: PR build

on: pull_request

concurrency:
  group: ci-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  smoke-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
          #- ubuntu-latest
        smoke-test-suite:
          - glassfish
          - jetty
          - liberty
          - tomcat
          - tomee
          - wildfly
          - other
        # THIS IS TEMPORARY TO FLUSH OUT SPORADIC FAILURES
        count:
          - 1
          - 2
          - 3
          - 4
          - 5
      fail-fast: false
    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
        if: matrix.os == 'windows-latest'

      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Restore cache
        uses: burrunan/gradle-cache-action@v1.10
        with:
          job-id: smokeTests
          read-only: true

      - name: Cache Gradle Wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-cache-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Test
        # using --no-daemon because windows builds have been sporadically running out of virtual memory
        run: ./gradlew :smoke-tests:test -PsmokeTestSuite=${{ matrix.smoke-test-suite }} --no-daemon
