name: Publish Quarkus images for smoke tests

on:
  push:
    paths:
      - 'smoke-tests/images/quarkus/**'
      - '.github/workflows/publish-smoke-test-quarkus-images.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      project: ":smoke-tests:images:quarkus"
      publish: true
      # Quarkus 2.0+ does not support Java 8
      skip-java-8: true

  open-issue-on-failure:
    needs: publish
    if: failure()
    uses: ./.github/workflows/reusable-open-issue-on-failure.yml
