name: Publish Quarkus images for smoke tests

on:
  push:
    paths:
      - 'smoke-tests/images/quarkus/**'
      - '.github/workflows/publish-smoke-test-quarkus-images.yml'
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    uses: ./.github/workflows/reusable-smoke-test-images.yml
    with:
      build-root-directory: smoke-tests/images/quarkus
      publish: true
      # Quarkus 2.0+ does not support Java 8
      skip-java-8: true

  issue:
    name: Open issue on failure
    needs: publish
    if: failure()
    uses: ./.github/workflows/reusable-create-issue-for-failure.yml
