name: PR build fake backend images for smoke tests

on:
  workflow_call:
    inputs:
      build-root-directory:
        type: string
        required: true
      publish:
        type: boolean
        required: false
      cache-read-only:
        type: boolean
        required: false
      skip-java-8:
        type: boolean
        required: false
      skip-java-17:
        type: boolean
        required: false
      skip-java-18:
        type: boolean
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11 for running Gradle
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Login to GitHub Package Registry
        if: ${{ inputs.publish }}
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Tag
        run: echo "TAG=$(date '+%Y%m%d').$GITHUB_RUN_ID" >> $GITHUB_ENV

      - name: Set up gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ inputs.cache-read-only }}

      - name: Build Java 8 Docker Image
        if: ${{ !inputs.skip-java-8 }}
        run: ./gradlew ${{ inputs.publish && 'jib' || 'jibDockerBuild' }} -PtargetJDK=8 -Djib.httpTimeout=120000 -Djib.console=plain
        working-directory: ${{ inputs.build-root-directory }}

      - name: Build Java 11 Docker Image
        run: ./gradlew ${{ inputs.publish && 'jib' || 'jibDockerBuild' }} -PtargetJDK=11 -Djib.httpTimeout=120000 -Djib.console=plain
        working-directory: ${{ inputs.build-root-directory }}

      - name: Build Java 17 Docker Image
        if: ${{ !inputs.skip-java-17 }}
        run: ./gradlew ${{ inputs.publish && 'jib' || 'jibDockerBuild' }} -PtargetJDK=17 -Djib.httpTimeout=120000 -Djib.console=plain
        working-directory: ${{ inputs.build-root-directory }}

      - name: Build Java 18 Docker Image
        if: ${{ !inputs.skip-java-18 }}
        run: ./gradlew ${{ inputs.publish && 'jib' || 'jibDockerBuild' }} -PtargetJDK=18 -Djib.httpTimeout=120000 -Djib.console=plain
        working-directory: ${{ inputs.build-root-directory }}
