name: Reusable - Shell script check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  shell-script-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Install shell check
        run: wget -qO- "https://github.com/koalaman/shellcheck/releases/download/stable/shellcheck-stable.linux.x86_64.tar.xz" | tar -xJv

      - name: Run shellcheck
        run: find -name '*.sh' | xargs shellcheck-stable/shellcheck --format=gcc
