name: Reusable - Muzzle

on:
  workflow_call:
    inputs:
      cache-read-only:
        type: boolean
        required: false

permissions:
  contents: read

jobs:
  muzzle:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - ":instrumentation:muzzle1"
          - ":instrumentation:muzzle2"
          - ":instrumentation:muzzle3"
          - ":instrumentation:muzzle4"
      fail-fast: false
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Free disk space
        run: .github/scripts/gha-free-disk-space.sh

      - name: Set up JDK for running Gradle
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
        with:
          distribution: temurin
          java-version: 17.0.6

      - name: Run muzzle
        uses: gradle/gradle-build-action@29c0906b64b8fc82467890bfb7a0a7ef34bda89e # v3.1.0
        with:
          arguments: ${{ matrix.task }}
          cache-read-only: ${{ inputs.cache-read-only }}
