name: Reusable - Markdown lint check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  markdown-lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install mardkdownlint
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: |
          markdownlint -c .markdownlint.yml -p .gitignore **/*.md -i licenses/licenses.md
